import * as crypto from 'crypto';

/**
 * Interface representing the structured ECIES ciphertext payload.
 */
export interface EncryptedPayload {
  ephemeralPublicKeyHex: string; // Ephemeral public key generated by sender
  ivHex: string;                 // 12-byte initialization vector for AES-GCM
  tagHex: string;                // 16-byte authentication tag from AES-GCM
  ciphertextHex: string;         // Encrypted representation of the amount string
}

/**
 * Helper to derive an AES-256 key from an ECDH shared secret using SHA-256.
 */
function deriveKey(sharedSecret: Buffer): Buffer {
  return crypto.createHash('sha256').update(sharedSecret).digest();
}

/**
 * Generates a new Auditor view keypair (secp256r1 / prime256v1).
 * Returns the private view key (hex) and public view key (hex).
 */
export function generateAuditorKeyPair(): { privateKeyHex: string; publicKeyHex: string } {
  const ecdh = crypto.createECDH('prime256v1');
  ecdh.generateKeys();
  return {
    privateKeyHex: ecdh.getPrivateKey('hex'),
    publicKeyHex: ecdh.getPublicKey('hex'),
  };
}

/**
 * Encrypts the private settlement amount off-chain using ECIES (ECDH + AES-GCM).
 * 
 * @param amount The private amount string to encrypt (e.g., "1000")
 * @param auditorPublicKeyHex The public key of the auditor (recipient)
 * @returns The structured EncryptedPayload
 */
export function encryptSettlement(amount: string, auditorPublicKeyHex: string): EncryptedPayload {
  // 1. Generate ephemeral ECDH keypair
  const ephemeralEcdh = crypto.createECDH('prime256v1');
  ephemeralEcdh.generateKeys();

  // 2. Compute ECDH shared secret against the auditor's public key
  const sharedSecret = ephemeralEcdh.computeSecret(Buffer.from(auditorPublicKeyHex, 'hex'));

  // 3. Derive 256-bit AES key using KDF (SHA-256)
  const aesKey = deriveKey(sharedSecret);

  // 4. Encrypt amount string using AES-256-GCM
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', aesKey, iv);
  
  let ciphertext = cipher.update(amount, 'utf8', 'hex');
  ciphertext += cipher.final('hex');
  const tag = cipher.getAuthTag();

  return {
    ephemeralPublicKeyHex: ephemeralEcdh.getPublicKey('hex'),
    ivHex: iv.toString('hex'),
    tagHex: tag.toString('hex'),
    ciphertextHex: ciphertext,
  };
}

/**
 * Decrypts the settlement payload using the auditor's private view key.
 * 
 * @param payload The EncryptedPayload containing ciphertext, ephemeral public key, IV, and tag
 * @param auditorPrivateKeyHex The private view key of the auditor (recipient)
 * @returns The recovered amount string
 * @throws Error if authentication fails (e.g. wrong key, corrupted payload)
 */
export function decryptSettlement(payload: EncryptedPayload, auditorPrivateKeyHex: string): string {
  // 1. Load the auditor's private key into ECDH
  const auditorEcdh = crypto.createECDH('prime256v1');
  auditorEcdh.setPrivateKey(Buffer.from(auditorPrivateKeyHex, 'hex'));

  // 2. Compute the shared secret using auditor's private key and ephemeral public key
  const sharedSecret = auditorEcdh.computeSecret(Buffer.from(payload.ephemeralPublicKeyHex, 'hex'));

  // 3. Derive the same 256-bit AES key
  const aesKey = deriveKey(sharedSecret);

  // 4. Decrypt using AES-256-GCM
  const decipher = crypto.createDecipheriv(
    'aes-256-gcm',
    aesKey,
    Buffer.from(payload.ivHex, 'hex')
  );
  decipher.setAuthTag(Buffer.from(payload.tagHex, 'hex'));

  let decrypted = decipher.update(payload.ciphertextHex, 'hex', 'utf8');
  decrypted += decipher.final('utf8'); // This will throw an error if the tag does not verify (wrong key/tampered)
  
  return decrypted;
}
